config/routes.rb
Rails.application.routes.draw do

  # match '/users/:id', to: 'users#show', via: 'get'
  # resources :users, :only =>[:show]
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'admin' => 'admin#index'

  resource   :user
  resources  :courses
  resources  :aplications
  resources  :comments
  resources  :instructors

  resources :courses, only: [:index, :show, :new, :create] do
   resources :comments, only: [:create, :destroy]
  end
  # devise_for :users,:controllers => { :new_user_registration => "users/registrations#new"}

  root 'homes#index'

end

app/models/aplication.rb
class Aplication < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :payment_method, presence: true, length: { maximum: 100}
end

app/controllers/aplications_controller.rb
class AplicationsController < ApplicationController
  before_action :set_aplication, only: [:show, :edit, :update, :destroy]
  before_action :superadmin_role_only, except: [:show, :new,:create]

    def index
      @aplications=Aplication.page(params[:page]).per(3)
    end

    def new
       @aplication= Aplication.new
       @courses = Course.all
     end

    def show

    end

    def create
      @aplication = Aplication.new(aplication_params)
       @aplication.user_id = current_user.id
        if @aplication.save
         redirect_to courses_path, notice: "Your application has been recorded!"
       else
         render :new
       end
     end

    def edit
    end

    def update
     @aplication=Aplication.new(aplication_params)
     if @aplication.update(aplication_params)
       redirect_to aplications_path, notice: " Course updated!"
       else
        render :edit
       end
    end

    def destroy
      @aplication.destroy
      redirect_to aplications_path, notice:" Course Deleted!"
    end

    private
    def superadmin_role_only
       unless current_user.superadmin_role?
         redirect_to courses_path, :notice => "Access denied! You need admin priviledges."
       end
     end

    def set_aplication
     @aplication = Aplication.find(params[:id])
    end

    def aplication_params
      params.require(:aplication).permit(:payment_method, :user_id, :id, :course_id)
    end
  end

app/views/aplications/_form.html.erb
<%= form_with(model: aplication, local: true) do |form| %>
  <% if aplication.errors.any? %>
    <div id="error_explanation">
      <h4><%= aplication.errors.count %> Errors Present.</h4>
      <ul>
      <% aplication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- <div class="page1"> -->


  <div class="field">
    <%= form.label :course %>
    <%= form.collection_select :course_id, Course.order(:name),:id,:name, required: true, class:'form-control' %>
  </div>


  <div class="field">
    <%= form.label :payment_method%>
    <%= form.select :payment_method, ['payment method', 'mobile money', 'Bank transfer','Cash payment'], class:'form-control'%>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"  %>
  </div>
<% end %>
<!-- </div> -->

app/views/aplications/edit.html.erb
<div class="apply">

  <h4>Editing Course Application Form</h4>

  <%= render 'form', course: @aplication%>

  <%= link_to 'Show', @aplication %> |
  <%= link_to 'Back', aplications_path %>
</div>

app/views/aplications/index.html.erb
<div class="apply">
  <h4>Application Form</h4>
  <table class="ui five column table">
    <thead>
      <tr>
        <th>Payment method</th>
          <th>Course name</th>
           <th>Course Description</th>
            <th>Course Period</th>
            <th>Application status</th>
            <th colspan="3"></th>
          </tr>
       </thead>
    <tbody>
      <tr>
      <% @aplications.each do |aplication| %>
      <td><%=aplication.payment_method %></td>
      <td><%=aplication.course.name %></td>
      <td><%=aplication.course.description %></td>
      <td><%=aplication.course.course_period %></td>
      <td><%= link_to 'Show', aplication %></td>
      <td><%= link_to 'Edit', edit_course_path(aplication) %></td>
      <td><%= link_to 'Destroy', aplication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Registration form', new_aplication_path, class: 'click' %>
  <a class= "nav-link"><%=paginate @aplications %></a>
</div>

app/views/aplications/new.html.erb
<div class="message">
  <div class="alert alert-info alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Info!</strong> Hello <%=current_user.first_name %>!
    Please select the course you want to enroll in. If you not sure, please feel free to contact us for assistance.
  </div>

<div class="page1">
  <!-- <h4 class='apply'>New application form</h4> -->
  <p class='new'><%= render 'form', aplication: @aplication, class: 'click' %></p>
  <p class='back'><%= link_to 'Return to Courses', courses_path, class: 'click' %></p>
</div>

app/views/aplications/show.html.erb
<div class="row justify-content-center">
  <div class="col-3">
    <div class="container">


      <p>
        <strong>payment_method:</strong>
        <%= @aplication.payment_method %>
      </p>

      <%= link_to 'Edit', edit_aplication_path(@aplication) %> |
      <%= link_to 'Back', aplications_path %>
    </div>
  </div>
</div>