config/routes.rb
Rails.application.routes.draw do

  # match '/users/:id', to: 'users#show', via: 'get'
  # resources :users, :only =>[:show]
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'admin' => 'admin#index'

  resource   :user
  resources  :courses
  resources  :aplications
  resources  :comments
  resources  :instructors

  resources :courses, only: [:index, :show, :new, :create] do
   resources :comments, only: [:create, :destroy]
  end
  # devise_for :users,:controllers => { :new_user_registration => "users/registrations#new"}

  root 'homes#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
 before_action :set_course, only: [:show, :edit, :update, :destroy]
 before_action :superadmin_role_only, except:[:show, :index]
  def index
    @q=Course.ransack(params[:q])
    @courses=@q.result(distinct: true).page(params[:page]).per(2)
  end

  def new
   @course=Course.new
  end

  def show
    @course=Course.find(params[:id])
    @comment= Comment.new
    @comment.course_id=@course.id
  end

  def create
   @course=Course.new(course_params)
     @course.user_id=current_user.id
       if @course.save
         redirect_to courses_path, notice: "New Course!"
       else
        render :new
      end
   end

  def edit
  end

  def update
   @course=Course.new(course_params)
     if @course.update(course_params)
        redirect_to courses_path, notice: " Course updated!"
     else
       render :edit
     end
  end

  def destroy
    @course.destroy
    redirect_to courses_path, notice:" Course Deleted!"
  end

  private
  def superadmin_role_only
     unless current_user.superadmin_role?
       redirect_to courses_path, :notice => "Access denied! You need admin priviledges."
     end
   end

  def set_course
   @course=Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name,:category,:description,:course_period,:user_id, :id)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_comment.html.erb

<div class="comment_section">
  <br>
  <p><%=comment.content %></p>
   <p class="click"><%=time_ago_in_words(comment.created_at)%> ago</p>
   <br>
     <% if comment.user %>
     <% if current_user.id==comment.user.id%>
     <i style='font-size:24px; color:#23689b'><%= link_to '', edit_comment_path(comment),class:'far fa-edit' %></i>|
     <i style='font-size:24px; color:red'><%= link_to '', comment, class: "fas fa-trash-alt", method: :delete, data: { confirm: 'Are you sure?' } %>
   </i>
   <% end %>
<% end %>
</div>

app/views/courses/_form.html.erb
<div class="page1">
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h4><%= course.errors.count %> Errors Present.</h4>
      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :category%>
    <%= form.select :category, ['Manual & Automatic', 'Manual', 'Automatic']%>
  </div>
  <div class="field">
    <%= form.label :description%>
    <%= form.text_field :description, placeholder:"description"%>
  </div>

  <div class="field">
    <%= form.label :course_period_weeks%>
    <%= form.text_field :course_period%>
  </div>
 <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/courses/edit.html.erb
<div class="page1">

<h4>Editing Course</h4>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>
</div>

app/views/courses/index.html.erb
<h4 class='top'>Course Panel</h4>
<div class="top-courses">
<div class="container">
  <div class="search">
    <%=search_form_for @q do |f| %>
    <%=f.label :name, class:'table-head' %>
    <%=f.search_field :name_cont, placeholder: 'course name' %>
    <%=f.select :category_cont, [" ",'Manual & Automatic', 'Manual', 'Automatic'], default: "category"%>
    <%=f.submit class:'search-button' %>
   <%end %>
 </div>
<table class="ui five column table">
  <thead>
    <tr>
      <th class='table-head'>Name</th>
      <th class='table-head'>Category</th>
      <th class='table-head'>Description</th>
      <th class= "sort_link"><%= sort_link(@q, :course_period, 'Course period(Weeks)', class: 'click', default_order: :desc) %></th>
      <th class='table-head'> Links</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td class="bar"><%=course.name %></td>
        <td class="bar"><%= course.category %></td>
        <td class="bar"><%= course.description %></td>
        <td class="bar"><%= course.course_period %></td>
        <td class="bar"><%= link_to 'comment', course, class: 'click' %></td>
        <td><%= link_to 'Apply', new_aplication_path, class: 'click' %></td>
        <% if can? :manage, User %>
        <td><%= link_to 'Edit', edit_course_path(course), class: 'click' %></td>
        <td><%= link_to 'Destroy', course, class: 'click', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<a class="move"><%=paginate @courses %></a><br>

<%= link_to 'Apply here', new_aplication_path, class: 'click' %>
<br>
<% if can? :manage, User %>
 <%= link_to 'Create new Course', new_course_path, class: 'click' %>
<% end %>

</div>
</div>


<!-- <a class="nav-link" href="#"></a> -->

app/views/courses/new.html.erb
 <div class="page1">
  <h4 class="move">New Course form</h4>

  <%= render 'form', course: @course %>

  
</div>

app/views/courses/show.html.erb
<div class="message">
  <div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Warning!</strong> Hello <%=current_user.first_name %>! Please leave us your review of the course in the comment section below and please observe good ethics when commenting. Enjoy
  </div>
</div>
<div class="comment">
  <div class="col-2">
    <div class="container">
      <p>
        <strong>Name:</strong>
        <%=@course.name %>
      </p>

      <p>
        <strong>Course category:</strong>
        <%=@course.category %>
      </p>

      <p>
        <strong>Course Description:</strong>
        <%=@course.description %>
      </p>

      <p>
        <strong>Course period:</strong>
        <%= @course.course_period %>
      </p>

      <p class="btn btn-primary" type="button">
        Comments <span class="badge"><%= @course.comments.size %></span>
      </p>
       <div class="ui card">
         <div class="content">
          <div class="header"><%=current_user.first_name %></div>
          <div class="meta">
            <span class="right floated time"></span>
            <span class="category"></span>
            </div>
            <div class="description">
              <p><%= render partial: 'courses/comment', collection: @course.comments.reverse %></p>
            </div>
          </div>
          <div class="extra content">
            <div class="right floated author">
            </div>
          </div>
        </div>
       <%= render partial: 'comments/form' %><br>
       <% if can? :manage, User %>
        <%= link_to 'Edit', edit_course_path(@course), class: 'click' %> |
       <%end%>
      <%= link_to 'Back', courses_path, class: 'click' %>
    </div>
  </div>
</div>