config/routes.rb
Rails.application.routes.draw do

  # match '/users/:id', to: 'users#show', via: 'get'
  # resources :users, :only =>[:show]
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'admin' => 'admin#index'

  resource   :user
  resources  :courses
  resources  :aplications
  resources  :comments
  resources  :instructors

  resources :courses, only: [:index, :show, :new, :create] do
   resources :comments, only: [:create, :destroy]
  end
  # devise_for :users,:controllers => { :new_user_registration => "users/registrations#new"}

  root 'homes#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

  <html lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title><%= content_for?(:title)? yield(:title): "SugoiSku" %></title>
       <%= csrf_meta_tags %>
       <%= stylesheet_link_tag "application", :media => "all" %>
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
       <script src="https://kit.fontawesome.com/d73c08515e.js" crossorigin="anonymous"></script>
       <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
       <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
       <%= javascript_include_tag "application" %>
   </head>
    <body>
 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
       <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>

   <div class="navbar navbar-default navbar-static-top">
       <div class="container">
           <a class="navbar-brand" href="#"><%= link_to 'Sugoi Driving School', root_path, class: "navbar-brand" %></a>
           <div class="navbar-collapse collapse navbar-responsive-collapse">
             <ul class="nav navbar-nav">

                   <% if can? :manage, User %>
             	    <li><%= link_to 'Admin Dashboard', admin_path, class: "menu" %></li>
                <% end %>
              </ul>

             <ul class="nav navbar-right col-md-4">
             <% if current_user %>
             <li class="col-md-8 user-name"
            <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.first_name, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
           </li>
           <li class="col-md-2"> </li>
           <li class="col-md-4 logout"><%= link_to('Logout', destroy_user_session_path, class:"btn btn-danger",
           title: 'Logout', :method => :delete) %></li>
          <% else %>
          <li class="col-md-4 pull-right">
          <%= link_to('Sign In', new_user_session_path, class: "btn btn-primary", title: 'Sign In') %>
          </li>
          <% end %>
          </ul>
        </div>
       </div>
      </div>
      <div class="sidebar">
        <br>
        <a class="bar"><%= link_to 'Home', root_path, class: "fas fa-home" %></a>
        <a class="bar"><%= link_to 'Courses', courses_path, class: "fas fa-car" %></a>
        <a class="bar"><%= link_to 'Instructors', instructors_path, class:"fas fa-address-card"%></a>
        <a class="bar"><%= link_to 'Apply', new_aplication_path, class: "fas fa-fill" %></a>
       <% if user_signed_in? %>
        <a class="bar"><%= link_to 'Profile', user_path(current_user), class:"fas fa-address-card" %></a>
       <% end %>

      </div>
      <div class="flash">
        <%=bootstrap_flash %>
      </div>
          <%= yield %>
  </body>

  <div class="bottom-container">
      <footer class="footer">
        <i class="fa fa-linkedin-square" style="font-size:22px; color:#23689b"><a class="footer-link" href="https://www.linkedin.com/">LinkedIn</a></i>
        <i class="fa fa-twitter-square" style="font-size:22px; color:#23689b"><a class="footer-link" href="https://twitter.com/">Twitter</a></i>

        <i class="fa fa-facebook-official" style="font-size:22px;color:#23689b"><a class="footer-link" href="https://www.appbrewery.co/">facebook</a></i>

        <p class="name">© 2021 sugoi.com.</p>
      </footer>
    </div>
</html>